from pathlib import Path
exec(open('lazor_solver.py').read().split('if __name__')[0])

bff = Path('examples/official/tiny_5.bff')
board, inventory, open_slots = parse_bff(bff)

print("=" * 60)
print("COORDINATE SYSTEM:")
print("3x3 grid in half-block coordinates:")
print()
print("   x: 0   1   2   3   4   5   6")
print("y=0:   |   |   |   |   |   |   ")
print("   1:   | (0,0) | (0,1) | (0,2) |")  
print("   2:   |   |   |   |   |   |   ")
print("   3:   | (1,0) | (1,1) | (1,2) |")
print("   4:   |   |   |   |   |   |   ")
print("   5:   | (2,0) | (2,1) | (2,2) |")
print("   6:   |   |   |   |   |   |   ")
print()
print("Laser starts at (4, 5) moving (-1, -1)")
print("  → That's at x=4 (between col 1 and 2), y=5 (at row 2)")
print()
print("Targets:")
print("  (1, 2) → x=1 (col 0), y=2 (between row 0 and 1)")
print("  (6, 3) → x=6 (past grid), y=3 (row 1)")
print()

print("=" * 60)
print("MANUAL TRACE with fixed B only:")
print("Grid: o B o / o o o / o o o")
print()
print("Step 0: Laser at (4, 5), direction (-1, -1)")
print("  Moving to (3, 4)")
print()
print("Step 1: At (3, 4), moving to (2, 3)")
print("  Crosses vertical edge at x=2 (between col 0 and 1)")
print("  Crosses horizontal edge at y=3 (between row 1 and 2)")
print("  Check cell at row 1, col 0 → 'o' (empty)")
print()
print("Step 2: At (2, 3), moving to (1, 2)")
print("  Crosses vertical edge at x=1")
print("  Crosses horizontal edge at y=2")
print("  Check cell at row 0, col 0 → 'o' (empty)")
print("  **At (1, 2) - TARGET HIT!**")
print()
print("Step 3: At (1, 2), moving to (0, 1)")
print("  Exits grid (x=0 is left boundary)")
print()
print("Conclusion: Only hits (1, 2), misses (6, 3)")
print()

print("=" * 60)
print("Why can't we hit (6, 3)?")
print("Target (6, 3) is at x=6 (right of grid), y=3 (row 1)")
print("Laser starts at (4, 5) moving LEFT and UP → will never reach x=6")
print()
print("**THIS PUZZLE MAY BE IMPOSSIBLE WITH THIS LASER!**")
